# Generated by Django 4.0.6 on 2022-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='URL_image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
